version: '3.8'
services:
  api:
    build: ./api
    container_name: pancong-inventori-api
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    depends_on:
      - postgres
    networks:
      - pancong_default
    restart: unless-stopped
    volumes:
      - ./api/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://pancongjaksel.store/api
    container_name: pancong-inventori-frontend
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - pancong_default
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: pancong_postgres
    environment:
      POSTGRES_USER: pancong_user
      POSTGRES_PASSWORD: 5f9b17c0fc3f450a330119ae843df3dc5ca33532e463627e
      POSTGRES_DB: pancong_inventori
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pancong_default
    restart: unless-stopped

networks:
  pancong_default:
    driver: bridge

volumes:
  postgres_data:
    external: true
    name: pancong_postgres_data
