const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { URL } = require('node:url');
if (!process.env.TEST_DATABASE_URL) throw new Error('TEST_DATABASE_URL wajib diisi untuk integration test Approval Center');
const u = new URL(process.env.TEST_DATABASE_URL);
const databaseName = u.pathname.slice(1);
if (!/(^|[_-])test([_-]|$)/i.test(databaseName)) {
  throw new Error('TEST_DATABASE_URL harus menunjuk database khusus test; test ini menjalankan TRUNCATE.');
}
process.env.JWT_SECRET='approval-test-secret'; process.env.PGHOST=u.hostname; process.env.PGPORT=u.port||'5432'; process.env.PGDATABASE=databaseName; process.env.PGUSER=decodeURIComponent(u.username); process.env.PGPASSWORD=decodeURIComponent(u.password); process.env.NODE_ENV='test';
const { pool } = require('../../db/pool');
const { kirimTransfer, verifikasiTransfer } = require('../../services/transferGudangService');
const express = require('express'); const http = require('node:http'); const { buatTokenUser, buatTokenDevice } = require('../../utils/jwt');
let fx;
async function reset(){ await pool.query("CREATE TABLE IF NOT EXISTS transaksi_masuk_nota (id SERIAL PRIMARY KEY,gudang_id INTEGER REFERENCES gudang(id),status_verifikasi VARCHAR(30) DEFAULT 'menunggu',diinput_oleh_role VARCHAR(30),nama_crew_input TEXT,created_at TIMESTAMPTZ DEFAULT now()); CREATE TABLE IF NOT EXISTS transaksi_masuk_item (id SERIAL PRIMARY KEY,nota_id INTEGER REFERENCES transaksi_masuk_nota(id),item_id INTEGER REFERENCES item(id),jumlah NUMERIC); ALTER TABLE users ADD COLUMN IF NOT EXISTS token_versi INTEGER NOT NULL DEFAULT 1;"); await pool.query('TRUNCATE stok_ledger, transaksi_verifikasi, api_idempotency, transfer_gudang, item, gudang, users RESTART IDENTITY CASCADE'); const g=await pool.query("INSERT INTO gudang(nama,tipe) VALUES ('UGM test','serving'),('Glagahsari test','serving') RETURNING id"); const o=await pool.query("INSERT INTO outlet(nama,gudang_asal_id) VALUES ('Outlet test',$1) RETURNING id",[g.rows[0].id]); const i=await pool.query("INSERT INTO item(kode_barang,nama,kategori,satuan) VALUES ('APP-TEST','Approval test','Kebersihan','Pack') RETURNING id"); const us=await pool.query("INSERT INTO users(nama,email,role) VALUES ('Owner test','owner@app','owner'),('AG test','ag@app','admin_gudang'),('Admin test','admin@app','admin') RETURNING id,role"); fx={a:g.rows[0].id,b:g.rows[1].id,outlet:o.rows[0].id,item:i.rows[0].id,owner:us.rows[0].id,ag:us.rows[1].id,admin:us.rows[2].id}; await pool.query("INSERT INTO stok_ledger(item_id,gudang_id,tipe_pergerakan,qty_delta,referensi_tabel,referensi_id,tanggal) VALUES($1,$2,'masuk',10,'test',1,CURRENT_DATE)",[fx.item,fx.a]);}
async function pending(qty=4){ return kirimTransfer({itemId:fx.item,gudangAsalId:fx.a,gudangTujuanId:fx.b,jumlah:qty,fotoBuktiKirimUrl:'test',dikirimOlehUserId:fx.ag,dikirimOlehRole:'admin_gudang'}); }
async function ledger(){ return (await pool.query("SELECT COALESCE(SUM(qty_delta),0) total, count(*)::int count FROM stok_ledger WHERE referensi_tabel='transfer_gudang'")).rows[0]; }
before(async()=>{await reset();}); after(async()=>pool.end());
test('pending tidak menulis ledger; approval stok cukup posting sekali', async()=>{ await reset(); const t=await pending(); assert.equal(t.status,'menunggu_approval'); assert.equal(Number((await ledger()).count),0); const out=await verifikasiTransfer({id:t.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'approve-1'}); assert.equal(out.status,'dikirim'); assert.equal(Number((await ledger()).total),-4); assert.equal(Number((await ledger()).count),1); });
test('stok tidak cukup saat approval tidak mengubah status/ledger', async()=>{ await reset(); const t=await pending(4); const session=await pool.query("INSERT INTO sesi_pengambilan_crew(nama_crew,gudang_asal_id,outlet_tujuan_id) VALUES('Crew test',$1,$2) RETURNING id",[fx.a,fx.outlet]); await pool.query("INSERT INTO sesi_pengambilan_item(sesi_id,item_id,qty) VALUES($1,$2,8)",[session.rows[0].id,fx.item]); await assert.rejects(()=>verifikasiTransfer({id:t.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'approve-low'})); const row=(await pool.query('SELECT status,status_verifikasi FROM transfer_gudang WHERE id=$1',[t.id])).rows[0]; assert.equal(row.status,'menunggu_approval'); assert.equal(row.status_verifikasi,'menunggu'); assert.equal(Number((await ledger()).count),0); });
test('dua approval bersamaan hanya satu ledger dan stok tidak negatif', async()=>{ await reset(); const t1=await pending(7); const t2=await pending(7); const r=await Promise.allSettled([verifikasiTransfer({id:t1.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'c1'}),verifikasiTransfer({id:t2.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'c2'})]); assert.equal(r.filter(x=>x.status==='fulfilled').length,1); assert.equal(Number((await ledger()).count),1); assert(Number((await pool.query('SELECT stok_saat_ini FROM v_stok_gudang_saat_ini WHERE gudang_id=$1 AND item_id=$2',[fx.a,fx.item])).rows[0].stok_saat_ini)>=0); });
test('reject terminal dan retry idempotency tunggal', async()=>{ await reset(); const t=await pending(); const rej=await verifikasiTransfer({id:t.id,ownerUserId:fx.owner,aksi:'reject',catatan:'tidak sesuai',idempotencyKey:'reject-1'}); assert.equal(rej.status,'ditolak'); assert.equal(rej.statusVerifikasi,'rejected'); await assert.rejects(()=>verifikasiTransfer({id:t.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'approve-after-reject'})); assert.equal(Number((await ledger()).count),0); const t2=await pending(); const a={id:t2.id,ownerUserId:fx.owner,aksi:'approve',idempotencyKey:'same-key'}; await verifikasiTransfer(a); await verifikasiTransfer(a); assert.equal(Number((await pool.query("SELECT count(*) FROM transaksi_verifikasi WHERE transaksi_id=$1",[t2.id])).rows[0].count),1); assert.equal(Number((await ledger()).count),1); });
test('HTTP Approval Center role boundary', async()=>{ await reset(); const app=express(); app.use(express.json()); app.use('/api/dashboard', require('../../routes/dashboard')); const server=await new Promise(resolve=>{const x=app.listen(0,()=>resolve(x));}); const port=server.address().port; async function get(token,device=false){const headers=device?{'X-Device-Token':token}:{Authorization:`Bearer ${token}`}; const r=await fetch(`http://127.0.0.1:${port}/api/dashboard/approval-center`,{headers}); return r.status;} const owner=buatTokenUser({userId:fx.owner,role:'owner',tokenVersi:1}); const admin=buatTokenUser({userId:fx.admin,role:'admin',tokenVersi:1}); const ag=buatTokenDevice({role:'admin_gudang',nama:'AG'}); assert.equal(await get(owner),200); assert.equal(await get(ag,true),200); assert.equal(await get(admin),403); assert.equal(await get(null),401); await new Promise(resolve=>server.close(resolve)); });
